name: universal_ble_server
description: "Cross-platform BLE peripheral plugin with AES encryption"
version: 0.0.1
homepage: https://example.com

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1

dev_dependencies:
  test: ^1.25.2
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.universal_ble_server
        pluginClass: UniversalBleServerPlugin
      ios:
        pluginClass: UniversalBleServerPlugin
      macos:
        pluginClass: UniversalBleServerPlugin
      windows:
        pluginClass: UniversalBleServerPlugin
      web:
        pluginClass: UniversalBleServerWeb
        fileName: universal_ble_server_web.dart
