name: universal_ble_server
description: "Cross-platform BLE peripheral plugin with AES encryption"
version: 0.0.1
homepage: https://github.com/arlamend7/flutter_universal_ble_server
repository: https://github.com/arlamend7/flutter_universal_ble_server
issue_tracker: https://github.com/arlamend7/flutter_universal_ble_server/issues
documentation: https://arlamend7.github.io/flutter_universal_ble_server
license: MIT
example: example/lib/main.dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.universal_ble_server
        pluginClass: UniversalBleServerPlugin
      ios:
        pluginClass: UniversalBleServerPlugin
      macos:
        pluginClass: UniversalBleServerPlugin
      windows:
        pluginClass: UniversalBleServerPlugin
      web:
        pluginClass: UniversalBleServerWeb
        fileName: universal_ble_server_web.dart
